#!/usr/bin/env python3
"""Trace the walkable paths of an organic district painting (Round 88).

Usage: python3 tools/build_organic_area.py <painting> <region> <art> [--path-rgb R,G,B[;R,G,B...]] [--tol N] [--clear x0,y0,x1,y1 ...]
  --clear: fractions of the image to force non-walkable (e.g. a sunbeam the tracer mistook for path).
  e.g. python3 tools/build_organic_area.py emerald.jpg elaris emerald

Writes assets/environment/areas/<art>.webp (1600x1000) and registers the
traced 400x250 walk mask in assets/organic-areas.js. Writes a preview with
the non-walkable ground darkened to /tmp/organic-<art>-preview.png.
"""
import base64, json, re, sys
import numpy as np
from PIL import Image
from scipy import ndimage as nd

args = sys.argv[1:]
if len(args) < 3: sys.exit(__doc__)
src, region, art = args[:3]
path_rgb = [(214, 170, 110), (176, 128, 80)]  # sandy and shaded dirt path
tol = 48
if '--path-rgb' in args: path_rgb = [tuple(int(v) for v in c.split(',')) for c in args[args.index('--path-rgb') + 1].split(';')]
if '--tol' in args: tol = int(args[args.index('--tol') + 1])

img = Image.open(src).convert('RGB')
img.resize((1600, 1000), Image.LANCZOS).save(f'assets/environment/areas/{art}.webp', quality=86)
a = np.asarray(img.resize((800, 500), Image.LANCZOS)).astype(int)
path = np.zeros(a.shape[:2], bool)
for c in path_rgb: path |= np.sqrt(((a - np.array(c)) ** 2).sum(2)) < tol
path = nd.binary_opening(path, iterations=1)              # drop speckles (sand on rocks, flowers)
path = nd.binary_closing(path, iterations=3)              # bridge pebbles and puddles on the path
lab, n = nd.label(path)
sizes = nd.sum(path, lab, range(1, n + 1))
keep = np.isin(lab, [i + 1 for i, s in enumerate(sizes) if s > 1500])  # only real path networks
walk = nd.binary_dilation(keep, iterations=2)             # include the soft path verge
for i, arg in enumerate(args):
    if arg == '--clear':
        for box in args[i + 1].split(';'):
            x0, y0, x1, y1 = (float(v) for v in box.split(','))
            walk[int(y0 * 500):int(y1 * 500), int(x0 * 800):int(x1 * 800)] = False
cells = walk.reshape(250, 2, 400, 2).mean((1, 3)) >= .5
bits = np.packbits(cells.flatten())
abc = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
flat = cells.flatten().astype(int)
flat = np.concatenate([flat, np.zeros((-len(flat)) % 6, int)])
mask = ''.join(abc[int(''.join(map(str, flat[i:i + 6])), 2)] for i in range(0, len(flat), 6))

out = 'assets/organic-areas.js'
try: text = open(out).read()
except FileNotFoundError: text = "'use strict';\n// Generated by tools/build_organic_area.py — traced walk masks for organic districts.\n"
line = f"ORGANIC_AREAS[{json.dumps(region + ':' + art)}] = {{ src: {json.dumps('assets/environment/areas/' + art + '.webp')}, mask: '{mask}' }};\n"
text = re.sub(r"ORGANIC_AREAS\[" + re.escape(json.dumps(region + ':' + art)) + r"\].*\n", '', text) + line
open(out, 'w').write(text)
prev = np.asarray(img.resize((800, 500))).copy(); big = np.kron(cells, np.ones((2, 2), bool)); prev[~big] = (prev[~big] * .3).astype(np.uint8)
Image.fromarray(prev).save(f'/tmp/organic-{art}-preview.png')
print(f'{art}: {cells.mean()*100:.1f}% walkable; mask written to {out}; preview /tmp/organic-{art}-preview.png')
